# Generated by Django 5.2.10 on 2026-01-21 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_alter_project_partner'),
        ('users', '0002_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='accepted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organisation.project'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
