# Generated by Django 5.2.10 on 2026-01-21 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_invitation_accepted_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set(),
        ),
    ]
