# Generated by Django 5.2.10 on 2026-01-21 13:29

import django.db.models.deletion
import organisation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'firm',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=organisation.models.task_attachment_path)),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'task_attachment',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=organisation.models.get_first_month_day)),
                ('is_one_time', models.BooleanField(default=True)),
                ('recurrence_pattern', models.CharField(blank=True, choices=[('weekly', 'Wöchentlich'), ('monthly', 'Monatlich'), ('quarterly', 'Vierteljährlich'), ('yearly', 'Jährlich')], max_length=20, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('finished', 'Abgeschlossen'), ('planned', 'In Planung'), ('cancelled', 'Storniert'), ('active', 'In Arbeit')], default='planned')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organisation.firm')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='organisation.firm')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
