# Generated by Django 5.2.10 on 2026-01-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Storniert'), ('active', 'Aktiv'), ('new', 'Neu'), ('completed', 'Fertig')], default='new', max_length=50),
        ),
    ]
