# Generated by Django 5.2.10 on 2026-01-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_task_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_veto',
            field=models.BooleanField(default=False),
        ),
    ]
