# Generated by Django 5.2.10 on 2026-01-21 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_task_is_veto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='organisation.firm'),
        ),
    ]
