# Generated by Django 5.2.10 on 2026-01-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_alter_project_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Storniert'), ('active', 'Aktiv'), ('new', 'Neu'), ('completed', 'Fertig'), ('expired', 'Abgelaufen')], default='new', max_length=50),
        ),
    ]
